apiVersion: v1
kind: Service
metadata:
  name: pxc-node2
  labels: 
    node: pxc-node2
spec:
  ports:
    - port: 3306
      name: mysql
    - port: 4444
      name: state-snapshot-transfer
    - port: 4567
      name: replication-traffic 
    - port: 4568
      name: incremental-state-transfer 
  selector:
    node: pxc-node2 

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pxc-node2 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        node: pxc-node2 
        unit: pxc-cluster
    spec:
      nodeSelector:
          node: ha2.dtdream.com
      containers:
        - resources:
            limits: 
              cpu: 1
          image: docker.dtdream.com/dtdream/percona_xtradb_cluster:5.7
          imagePullPolicy: Always
          name: pxc-node2
          ports:
            - containerPort: 3306
            - containerPort: 4444
            - containerPort: 4567
            - containerPort: 4568
          livenessProbe:
            exec:
              command:
              - mysqladmin ping -u root -pDtDream@0209
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: GALERA_CLUSTER
              value: "true"
            - name: WSREP_CLUSTER_ADDRESS
              value: gcomm://
            - name: WSREP_SST_USER
              value: sst
            - name: WSREP_SST_PASSWORD
              value: sst
            - name: MYSQL_USER
              value: dtdream
            - name: MYSQL_PASSWORD
              value: DtDream@0209
            - name: MYSQL_ROOT_PASSWORD
              value: DtDream@0209
