apiVersion: v1
kind: Service
metadata:
  name: pxc-node1
  labels:
    node: pxc-node1
spec:
  ports:
    - port: 3306
      name: mysql
    - port: 4444
      name: state-snapshot-transfer
    - port: 4567
      name: replication-traffic 
    - port: 4568
      name: incremental-state-transfer 
  selector:
    node: pxc-node1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pxc-node1 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        node: pxc-node1 
        unit: pxc-cluster
      # Comment the following annotation if Dashboard must not be deployed on master
#      annotations:
#        scheduler.alpha.kubernetes.io/tolerations: |
#          [
#            {
#              "key": "dedicated",
#              "operator": "Equal",
#              "value": "master",
#              "effect": "NoSchedule"
#            }
#          ]
    spec:
      nodeSelector:
          node: ha1.dtdream.com
      containers:
        - resources:
            limits: 
              cpu: 1
          image: docker.dtdream.com/dtdream/percona_xtradb_cluster:5.7
          imagePullPolicy: Always
          name: pxc-node1
          ports:
            - containerPort: 3306
            - containerPort: 4444
            - containerPort: 4567
            - containerPort: 4568
          livenessProbe:
            exec:
              command:
              - mysqladmin ping -u root -pDtDream@0209
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: GALERA_CLUSTER
              value: "true"
            - name: WSREP_CLUSTER_ADDRESS
              value: gcomm://
            - name: WSREP_SST_USER
              value: sst
            - name: WSREP_SST_PASSWORD
              value: sst
            - name: MYSQL_USER
              value: dtdream
            - name: MYSQL_PASSWORD
              value: DtDream@0209
            - name: MYSQL_ROOT_PASSWORD
              value: DtDream@0209
